### ISSUE TITLE
HA Bridge running on port 82

### ISSUE THREAD

**Issue by nilsbernhar** [stampe123/node-red-contrib-node-hue#13]
Hello,

I have an HA bridge up and running on port 82. all of my other devices don't seem to have a problem with this (alexa and logitech harmony). Sadly though, I was not able yet to integrate my habridge into node-red.
All of the nodes available seem to be using port 80 as standard...

Does anyone have an Idea how to solve this?

Thanks in advance!

**Comment by jdomeij** [comment]
Using "address:port" it is now possible to use ports other than 80
