### ISSUE TITLE
Color changes, though no command given for that

### ISSUE THREAD

**Issue by brammh** [stampe123/node-red-contrib-node-hue#14]
Most likely I'm doing something wrong. I use a message to turn on the lights of a group to a certain level. using this payload: {"on": true,"bri": 80,"duration": 10}
The funny thing is that the color is also changing to some purple / pink color (no matter what the color before the transaction was). I only want to change the brightness. where is the command to change color coming from?
thnx,
bram

**Comment by jdomeij** [comment]
When changing one parameter the node would push all its values to the light, I have upload and new version that limits the node to only push out changed parameters.
