### ISSUE TITLE
Server not found or not activated

### ISSUE THREAD

**Issue by weevilofdoom** [stampe123/node-red-contrib-node-hue#16]
Hi,

First of all I'm new to Node-red and linux so take it easy! I'm trying to recreate the Dashboard example on the main page, but I'm having an issue. In the node-hue-out node, I've linked the bridge and have a valid bridge authentication key, but when I click on the magnifying glass beside the Light ID, I get an error saying 'Server not found or not activated'

I'm using Node Red v0.17.5 with node.js 8.9.4 on a Raspberry Pi. I've tried deleting the node and recreating it, but still get the error when trying to select the light.  There are also no errors or warnings when node-red starts up (see screengrab below).

What am I doing wrong?
![image](https://user-images.githubusercontent.com/35310177/34794176-c173dab6-f645-11e7-928d-f0795665046b.png)

Al

**Comment by jdomeij** [comment]
This is an limitation in the design, the problem is for the server to start it needs at-least one node running.
The easiest ways is to add light with id "light1", after it has been activated the server should run and it should now be able to list all nodes
