### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by philipsoeberg** [stampe123/node-red-contrib-node-hue#18]
Your README.md and red/hue-input.html say:
>>`cr`, `mired` or `mirek`<< with **cr**, not **ct** which in fact is what the HUE API and your excellent component accepts (in and out). A simple Documentation typeo in two places :)
Correct should be >>`ct`, `mired` or `mirek`<< in both places.

**Comment by jdomeij** [comment]
Ahh thanks, will fix it (and close this issue) in the future.

**Comment by jdomeij** [comment]
Fixed
