### ISSUE TITLE
Typo in out node

### ISSUE THREAD

**Issue by tedstriker** [stampe123/node-red-contrib-node-hue#2]
I guess it's not a Lifx server in the hue out node
<img width="493" alt="typo" src="https://cloud.githubusercontent.com/assets/795203/22280749/18168986-e2d3-11e6-92f8-51d684d57383.png">

**Comment by jdomeij** [comment]
Ahhh thanks, will fix

**Comment by jdomeij** [comment]
This has been fixed for a long time
