### ISSUE TITLE
Toggle

### ISSUE THREAD

**Issue by iChUdY** [stampe123/node-red-contrib-node-hue#20]
Pls add toggle msg to input node. For one stateless button ON/OFF.

**Comment by maragelis** [comment]
Can you not do this with a trigger node ?

**Comment by jdomeij** [comment]
I have added an "toggle" keyword for the "on" property, for it to work good you should also send an brightness because it becomes zero when the light is turned off

**Comment by iChUdY** [comment]
Thanks 👍🏻

**Comment by RaymondMouthaan** [comment]
Thanks 👍 

Please add to the documentation :-)
