### ISSUE TITLE
100% Brightness - 39% Brightness?

### ISSUE THREAD

**Issue by TerryLansdown** [stampe123/node-red-contrib-node-hue#21]
Hi,

Thanks for the code, working well so far. One problem I’ve noticed, if I inject the following JSON via MQTT, my hue lights switch on, but don’t seem to set the brightness correctly to 100%, I’ve tried with  both 255 or “100%”, but either seems to set the brightness to 39% (in the Home app).
```
{
    "on": [
        true
    ],
    "transitiontime": [
        0
    ],
    "bri": [
        "100%"
    ]
}
```

Thanks for any help you can offer.

**Comment by jdomeij** [comment]
The problem most likely is because you pass the values in an array, and also the brightness should be an number not an string

Try changing the JSON to something like this
```json
{
  "on": true,
  "duration": 0,
  "bri": 100
}
```

**Comment by TerryLansdown** [comment]
Hi, 

Thanks. No difference, I'm afraid. I'm guessing it's something to do with the "bri": 100, which is 39% more or less of 255. 

Tried with 255 or 254, or "100%", or 50, but no change, the light/s just come on at 39%. Any other thoughts?

**Comment by TerryLansdown** [comment]
Figured it out, I had a function elsewhere that was setting the msg.payload to 100 not 254. I needed to pass the values as my post above to avoid a 'TypeError: CreateListFromArrayLike called on non-object
' error.

Thanks and apologies for the dumb error.
