### ISSUE TITLE
unreachable state

### ISSUE THREAD

**Issue by Isaksson** [stampe123/node-red-contrib-node-hue#22]
When using in Node-RED the node will not report when a device goes to unreachable.
Same with both Groups and Lights.

**Comment by jdomeij** [comment]
I have published an new version that should fix the problem

**Comment by Isaksson** [comment]
Perfect, I will test this new version.

**Comment by Isaksson** [comment]
It seems to work on the lights but not on a group.
That is not any big issue, its fine with just the lights, thanks.

**Comment by jdomeij** [comment]
Groups doesn't seem to have any unreachable state, even if all lights in an group is unreachable the group is still not marked as such.
Tested both in the Hue app and looking at the raw data from the node-hue-api lib
