### ISSUE TITLE
Hub(s) 'undefined'

### ISSUE THREAD

**Issue by TerryLansdown** [stampe123/node-red-contrib-node-hue#23]
Hi, thanks, I'm enjoying the hue node-red integration.

One issue I've noticed…I have two bridges, and both appear in the UI as 'undefined' in the pop-up. How can I rename the devices? 

Thanks, Terry

**Comment by jdomeij** [comment]
The `Unknown` is probably some bug. I use the nuPnP function to detect the devices, this only returns name and id. To get the device node I would need to create another step that queries the devices for their names, which is non trivial (timeout handling).
When you create an bridge node you can set your own name that will be used when configuring the lights.

**Comment by TerryLansdown** [comment]
> The Unknown is probably some bug. I use the nuPnP function to detect the devices, this only returns name and id. To get the device node I would need to create another step that queries the devices for their names, which is non trivial (timeout handling).
> When you create an bridge node you can set your own name that will be used when configuring the lights.

Thanks, sounds like that’s not worth the effort.

When I add a bridge node, I don’t see an option to name the Bridge/s. In my setup I have either Hue Pull or Hue Set, neither seems to offer an option to define the name for the Bridge(s). Apologies if I’m missing something obvious.

Thanks, Terry

**Comment by jdomeij** [comment]
When adding an hue input/output node you need to add/select bridge node, on this page you can set the name of the hub

**input/output node**
![image](https://user-images.githubusercontent.com/16639651/43162124-57c0fe9e-8f8a-11e8-9d15-94e74c6f01f7.png)

**bridge node**
![image](https://user-images.githubusercontent.com/16639651/43162347-06d16004-8f8b-11e8-9651-a00e2b4903d8.png)

**Comment by TerryLansdown** [comment]
That’s interesting, but not what I see, see attached.

> When adding an hue input/output node you need to add/select bridge node, on this page you can set the name of the hub
> 
> input/output node
> 
> 
> bridge node

**Comment by jdomeij** [comment]
"Hue Pull" and "Hue Set" is the nodes from "node-red-contrib-hue" which is another hue package
