### ISSUE TITLE
Input from motion detector?

### ISSUE THREAD

**Issue by devleaks** [stampe123/node-red-contrib-node-hue#24]
Philips Hue Motion Detector fires events on motion detection (!). It would be great if we could capture them in your package. [I've read](https://www2.meethue.com/en-us/p/hue-motion-sensor/046677473389) that the motion detector also reports light level and it would be great if we could get that. (Turn light on when light level below 50 lux.)
Thank you.

**Comment by jdomeij** [comment]
I have no plans for adding input nodes to this package at this moment, the only way to detect events is poll for them. The light nodes uses slow polling mode to keep the node-red and the lights synchronized, this doesn't work when handling event driven inputs where you need to continuously poll with low delay to not make it feel unresponsive.
I'm uncertain how to integrate this with the existing code and how large redesign is needed

**Comment by devleaks** [comment]
OK. Thanks for the feedback. P.
