### ISSUE TITLE
parameter, username, not available

### ISSUE THREAD

**Issue by K-RAD** [stampe123/node-red-contrib-node-hue#26]
Trying to set up the bridge and when I click the Register User button, I get "parameter, username, no available"

**Comment by RaymondMouthaan** [comment]
Have you pressed the bridge button while trying?

**Comment by K-RAD** [comment]
Many times

**Comment by K-RAD** [comment]
![image](https://user-images.githubusercontent.com/3822874/43840102-19998cde-9b20-11e8-97c5-cbb70e57e01e.png)

**Comment by RaymondMouthaan** [comment]
Have you restarted the bridge ?

**Comment by K-RAD** [comment]
Yes. Is this something that this is accounted for?
https://github.com/shokai/node-philips-hue/pull/13

**Comment by K-RAD** [comment]
So I followed [these instructions](https://developers.meethue.com/documentation/getting-started) to create an auth code myself. Now I can see all my lights in the Light ID list, however when I try to use them, I get "Cannot read property 'on' of undefined"

**Comment by K-RAD** [comment]
I had to also restart the node-red server and now everything seems to be working fine (at least, I think)
