### ISSUE TITLE
Unable to retrieve light list, select lights.

### ISSUE THREAD

**Issue by jhaury** [stampe123/node-red-contrib-node-hue#5]
Hello, I have installed the node and it installs just fine, but I am having issues trying to use it. I am able to add my bridge and I am able to get an API when I press the bridge button. But whenever I try to get a list of my lights I get an error "Server not found or activated". I have tried on an Ubuntu server and two other Raspberry Pies, same result.

**Comment by jdomeij** [comment]
Hello, have you tried to activate the server node before trying to list the lights, I have a vague memory that this was required to get the base system up and running so it could query the available lights.

**Comment by Miloune** [comment]
@jdomeij What do you mean by activate the server node ? (I got the same problem)

**Comment by fmartingr** [comment]
Just happened this to me, you just need to deploy the flow without the configuration but adding the hue first, after the deploy a hue server is run in the background and the light selector works.

**Comment by jhaury** [comment]
Thanks you fmartingr, tried that out and it worked perfectly.
