### ISSUE TITLE
Light External Reference

### ISSUE THREAD

**Issue by lespatots** [stampe123/node-red-contrib-node-hue#6]
I need to be able to pass the light id into the node rather than it being fixed by the node setup. This would allow for a single node to be driven by a database of hue information. Is it possible to change the coding to allow this if no light ID is set. It would also be helpful if the same applied for the hub and then more than one hub could also be chosen. This would of course be a two way information flow where the light status data could be stored in the database.

I just had a thought that Topic might be a better place to pass this via?

**Comment by jdomeij** [comment]
Hmmm I see no reason of implement this, to work around the limitation with polling mode the module needs to keep track of all changes which is why it has the current design. 
The thing you want is only an thin node-red wrapper around the [node-hue-api](https://www.npmjs.com/package/node-hue-api)
