### ISSUE TITLE
Feature request: Example Node-RED flow

### ISSUE THREAD

**Issue by tomcollis** [stampe123/node-red-contrib-node-hue#9]
Hi,
It would be great as a starting point to provide the example node-red flow that you used in the screenshot so that it can be copy and pasted into Node-RED.
Great node btw,
Thank You

**Comment by roccomuso** [comment]
+1 thanks! That could be put inside the `example` directory.

**Comment by jdomeij** [comment]
`demo_flow.json` has been added to the example folder
